---
builds:
  - id: main
    main: cmd/jsonstruct
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ignore:
      - goos: windows
        goarch: arm64
archives:
  - id: main
    builds:
      - main
    format: tar.gz
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  use: github-native
  abbrev: 0
  sort: asc
  filters:
    exclude:
      - typo
