---
name: test
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: FuzzParser
        run: go test -v -fuzztime 60s -fuzz "FuzzParser"

      - name: FuzzGetGoName
        run: go test -v -fuzztime 60s -fuzz "FuzzGetGoName"
